# This is a basic workflow to help you get started with Actions

name: Bazel Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# Jobs run in parallel by default
jobs:

  build:
    name: Bazel Test

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Mount Bazel Cache
        uses: actions/cache@v1
        with:
          path: /home/runner/.cache
          key: bazel-cache-v0.0.1

      - name: Install Bazelisk via bin/setup
        run: |
          BAZEL_HOME=/home/runner/.cache/bazel bin/setup
          mkdir -p /home/runner/.cache/bazel \
                   /home/runner/.cache/bazel-out \
                   /home/runner/.cache/bazel-cache

      - name: Install .bazelrc for CI
        run: |
          cat <<EOF > .bazelrc.user
          build --disk_cache=/home/runner/.cache/bazel-cache
          startup --output_base=/home/runner/.cache/bazel-out
          EOF

      - name: Bazel Build
        run: |
          bazel build //...:all

      - name: Bazel TestAll
        run: |
          bazel test //...:all --test_output=errors

      - name: Bazel Lint
        run: |
          bazel run //:buildifier-check
