name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v .

    - name: Test
      run: |
        go test -v -race -coverprofile=coverage.txt -covermode=atomic \
          ./internal/common/imei \
          ./internal/common/luhn \
          ./internal/client \
          ./internal/server

    - name: Submit Test Coverage
      run: |
        CODECOV_TOKEN="8ebf3f30-55d8-4a9d-8c99-c5f3eef2a713" 
        bash <(curl -s https://codecov.io/bash)

    - name: Go Specs
      run: |
        export GOPATH=$(dirname $(which go))
        export PATH=$GOPATH/bin:$PATH
        echo "GOPATH=$GOPATH"
        echo "PATH=$PATH"
        go get github.com/onsi/ginkgo/ginkgo
        go get github.com/onsi/gomega/...
        ginkgo ./internal/common/*

